# Generated by Django 2.1.1 on 2018-12-22 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OfficeHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='bookable',
            name='officehour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booker.OfficeHour'),
        ),
    ]
