# Generated by Django 2.1.1 on 2018-12-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officehour',
            name='date',
        ),
        migrations.AlterField(
            model_name='bookable',
            name='starttime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='officehour',
            name='endtime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='officehour',
            name='starttime',
            field=models.DateTimeField(),
        ),
    ]
